#ifdef SPANISH
	#define STR0001 "Generacion de DDE"
	#define STR0002 "Buscar"
	#define STR0003 "Visualizar"
	#define STR0004 "Generar"
	#define STR0005 "Volver"
	#define STR0006 "íEl directorio Para grabacion de txt no existe ("
	#define STR0007 ") !"
	#define STR0008 "Aviso"
	#define STR0009 "Proceso de exportacion anulado"
	#define STR0010 "Proceso no tiene datos para visualizar. íGenere la DDE primero !"
	#define STR0011 "Atencion"
	#define STR0012 "íProceso ya posee numero de DDE !"
	#define STR0013 "Proceso esperando retorno del Siscomex. ¿Quiere generar nuevamente ?"
	#define STR0014 "Incluir"
	#define STR0015 "Modificar"
	#define STR0016 "Borrar"
	#define STR0017 "Procesando archivo temporal"
	#define STR0018 "íProceso esperando la generacion de la DDE !"
	#define STR0019 "Inclusion"
	#define STR0020 "Modificacion"
	#define STR0021 "Visualizacion"
	#define STR0022 "Borrado"
	#define STR0023 "No hay datos Para "
	#define STR0024 "."
	#define STR0025 "íC.G.C./C.P.F. no registrado !"
	#define STR0026 "íPeso neto total no puede ser negativo !"
	#define STR0027 "íPeso bruto total no puede ser negativo !"
	#define STR0028 "íValor total en la condicion de venta no puede ser negativo !"
	#define STR0029 " ídebe ser blanco o haber un Valor numerico !"
	#define STR0030 "Cantidad no puede ser negativa. íDigite espacios o ceros o un Valor positivo !"
	#define STR0031 "Error en la creacion del archivo: "
	#define STR0032 "Error en la creacion del archivo: "
	#define STR0033 "íArchivo generado con exito !"
	#define STR0034 "Error en el DOS num. "
	#define STR0035 "Todos"
	#define STR0036 "Finalizados"
	#define STR0037 "Pendientes"
	#define STR0038 "Pedido"
	#define STR0039 "Secuencia"
	#define STR0040 "Cod. Item"
	#define STR0041 "Descripcion"
	#define STR0042 "Precio Unit."
	#define STR0043 "Unid.medida"
	#define STR0044 "Cantidad "
	#define STR0045 "Vlr.total  "
	#define STR0046 "Referencia Cliente"
	#define STR0047 "Retorno Siscomex"
	#define STR0048 "Procesos:"
	#define STR0049 "No hay Itemes Para esta seleccion."
	#define STR0050 " Datos del proceso de Embarque: "
	#define STR0051 "Detalles del archivo de retorno : "
	#define STR0052 "Nombre         : "
	#define STR0053 "Tamaño      : "
	#define STR0054 " bytes"
	#define STR0055 "Fecha generacion : "
	#define STR0056 "Hora generacion : "
	#define STR0057 "Contenido del archivo "
	#define STR0058 "de error:"
	#define STR0059 "PreParar"
	#define STR0060 "Proceso no tiene DDE preParada. íPrepare la DDE primero !"
	#define STR0061 "Generacion de DSE"
	#define STR0062 "Proceso no tiene datos por visualizar. ¡Genere la DSE primero !"
	#define STR0063 "¡Proceso ya tiene numero de DSE !"
	#define STR0064 "Proceso no tiene DSE preparada. ¡Prepare la DSE primero !"
	#define STR0065 " de DSE no permitida para este embarque, pues existen items con RE o DDE."
	#define STR0066 " de DSE no permitida para este embarque, pues el mismo ya se encuentra embarcado."
	#define STR0067 "Preparacion"
	#define STR0068 "Generacion"
	#define STR0069 "F/Serie: "
	#define STR0070 "La Tabla con la Conversion de Unidad de Medida no esta activa. Active la tabla e informe las conversiones para las unidades de medida."
	#define STR0071 "Seleccione la forma de agrupacion"
	#define STR0072 "Agrupacion"
	#define STR0073 "Item"
	#define STR0074 "N.C.M."
	#define STR0075 "Proceso sin generacion de DSE. Primero se debe generar la DSE para obtener el retorno despues."
	#define STR0076 "Archivo de retorno no encontrado."
	#define STR0077 "Retorno de la DSE"
	#define STR0078 "Proceso : "
	#define STR0079 "Nº DSE  : "
	#define STR0080 "Fecha     : "
	#define STR0081 "Hora     : "
	#define STR0082 "Para confirmar el retorno de la DSE, elija el boton Ok, en caso contrario"
	#define STR0083 "Anular."
	#define STR0084 "Se encontraron unidades de medidas sin el registro en la tabla de Conversion de Unidades."
	#define STR0085 "  De  "
	#define STR0086 " A "
	#define STR0087 "Para finalizar la generacion de la DSE es necesario que las unidades de medidas"
	#define STR0088 "relacionadas, se registren en la tabla de conversion de unidades."
	#define STR0089 "Conversion de la unidad de medida"
	#define STR0090 "Retorno de la DSE finalizada con exito."
	#define STR0091 "La clave de identificacion del proceso que se encuentra en el archivo de retorno es invalida."
	#define STR0092 "Revertir"
	#define STR0093 "Proceso sin preparacion de "
	#define STR0094 " para revertir."
	#define STR0095 "Confirma la reversion de la preparacion y generacion de la "
	#define STR0096 "Reversion de la "
	#define STR0097 " finalizado con exito."
	#define STR0098 "Retorno"
	#define STR0099 "Reversion"
	#define STR0100 "La especie no se relleno. Prrimero informe la especie, para despues informar la Ctd."
	#define STR0101 "¡Sucursal del Exterior no puede generar datos para SISCOMEX !"
	#define STR0102 "En la carpeta "
	#define STR0103 ", o campo Tipo näo foi preenchido. Devido o campo "
	#define STR0104 " es igual a Si y obligatorio el rellenado del campo "
	#define STR0105 "N carpeta "
	#define STR0106 ", el campo "
	#define STR0107 " no se relleno. El mismo debe rellenarse para confirmacion de la preparacion."
	#define STR0108 "No fue posible caregar el archivo EXL. Verifique si el mismo, se encuentra en el diccionario de datos en la base de datos. En caso de dudas entre en contacto con el soporte tecnico de Average Tecnologia."
	#define STR0109 "Total de facturas"
	#define STR0110 "Informe la factura inicial."
	#define STR0111 "La factura informada es invalida. La factura debe informarse de la siguiente forma: Fc.01, en la que 01 es el numero de la Factura."
	#define STR0112 "Informe la factura de final."
	#define STR0113 "La factura informada es invalida. La factura debe informarse de la siguiente forma: Fc.09, en la que 09 es el numero de la factura."
	#define STR0114 "Para concluir la generacion de DDE es necesario que las unidades de medida"
	#define STR0115 " a "
	#define STR0116 "CNPJ/CPF de Representante Legal no informado."
	#define STR0117 "El campo "
	#define STR0118 " debe informarse, debido el campo "
	#define STR0119 " estar completo."
	#define STR0120 "¿Confirma el borrado de la factura?"
	#define STR0121 "¿Confirma la recuperacion de la factura?"
	#define STR0122 "El Gestor con el CPF informado no fue encontrado en el registro de empresas."
	#define STR0123 "Antes de la Geración es necesario procesar las rutinas de respuesta."
#else
	#ifdef ENGLISH
		#define STR0001 "DDE Generation"
		#define STR0002 "Search"
		#define STR0003 "View"
		#define STR0004 "Generate"
		#define STR0005 "Return"
		#define STR0006 "There is no directory to record the txt ("
		#define STR0007 ") !"
		#define STR0008 "Warning"
		#define STR0009 "Export process cancelled"
		#define STR0010 "Processo nao possui dados a visualizar. Gere a DDE primeiro !"
		#define STR0011 "Warning"
		#define STR0012 "Process already holds DDE number  !"
		#define STR0013 "Process waiting for a Sixcomex return. Do you want to generate it again ?"
		#define STR0014 "Insert"
		#define STR0015 "Edit"
		#define STR0016 "Delete"
		#define STR0017 "Processing Temporary File"
		#define STR0018 "Process waiting for a DDE generation  !"
		#define STR0019 "Insert"
		#define STR0020 "Edit"
		#define STR0021 "View"
		#define STR0022 "Deletion"
		#define STR0023 "There are no data for "
		#define STR0024 "."
		#define STR0025 "C.G.C./C.P.F. não cadastrado !"
		#define STR0026 "Total net weight cannot be negative  !"
		#define STR0027 "Total gross weight cannot be negative  !"
		#define STR0028 "Total value referring to the sales term cannot be negative  !"
		#define STR0029 " must be in blank or hold a numerical value  !"
		#define STR0030 "Quantity cannot be negative. Enter a positive value !                     "
		#define STR0031 "Error while creating file: "
		#define STR0032 "Error creating file: "
		#define STR0033 "File generated successfully!"
		#define STR0034 "DOS no. error "
		#define STR0035 "All"
		#define STR0036 "Concluded"
		#define STR0037 "Pending"
		#define STR0038 "Order"
		#define STR0039 "Sequence"
		#define STR0040 "Cod. Item"
		#define STR0041 "Description"
		#define STR0042 "Unit Price"
		#define STR0043 "Unit. Meas."
		#define STR0044 "Quantity "
		#define STR0045 "Total Vl.  "
		#define STR0046 "customer Reference"
		#define STR0047 "Siscomex Return"
		#define STR0048 "Processs:"
		#define STR0049 "There are no items for this selection."
		#define STR0050 "Shipment Process Data:  "
		#define STR0051 "Return file details  :  "
		#define STR0052 "Name         : "
		#define STR0053 "Size      : "
		#define STR0054 " bytes"
		#define STR0055 "Error:"
		#define STR0056 "generation date  :  "
		#define STR0057 "File Contents "
		#define STR0058 "generation hour  :  "
		#define STR0059 "Set up"
		#define STR0060 "Process does not hold DDE set up. First set up the DDE !"
		#define STR0061 "DSE generation"
		#define STR0062 "Process has no data to be viewed. Generate a DSE first!      "
		#define STR0063 "Process already has a DSE number! "
		#define STR0064 "Process has no DSE prepared. Prepare a DSE first!       "
		#define STR0065 " of DSE not allowed for this shipment because there are items with RE or DDE"
		#define STR0066 " of DSE not allowed for this shipment because it is already shipped.            "
		#define STR0067 "Preparat. "
		#define STR0068 "Generat."
		#define STR0069 "Inv/Serie:"
		#define STR0070 "Unit of measurement conversion table is inactive. Active a table and enter the conversions for the units of measurement.        "
		#define STR0071 "Select a way of grouping        "
		#define STR0072 "Grouping   "
		#define STR0073 "Item"
		#define STR0074 "N.C.M."
		#define STR0075 "Process without DSE generation. First, a DSE must be generated to obtain an answer.   "
		#define STR0076 "Return file not found.            "
		#define STR0077 "DSE return    "
		#define STR0078 "Process:   "
		#define STR0079 "DSE Nbr. : "
		#define STR0080 "Date     : "
		#define STR0081 "Time     : "
		#define STR0082 "To confirm return of a DSE, select the OK button, otherwise,       "
		#define STR0083 "Cancel.  "
		#define STR0084 "Units of measurement were found without registration in the Unit Conversion table.      "
		#define STR0085 " From "
		#define STR0086 " To   "
		#define STR0087 "To finish generating the DSE,  it is necessary that the units of meas."
		#define STR0088 "listed are registered in the unit conversion table.                "
		#define STR0089 "Conversion of unit of measur. "
		#define STR0090 "DSE return finished successfully.    "
		#define STR0091 "Process identification key in the return file is invalid.                             "
		#define STR0092 "Reverse "
		#define STR0093 "Process s/o preparation of "
		#define STR0094 " to reverse.   "
		#define STR0095 "Confirm reversal of preparation and generation of"
		#define STR0096 "Reversal of"
		#define STR0097 " finished successfully."
		#define STR0098 "Return "
		#define STR0099 "Reversal"
		#define STR0100 "Species not entered. First, enter a species in order to be able to enter a quantity. "
		#define STR0101 "Branch abroad cannot generate data for SISCOMEX!         "
		#define STR0102 "In folder"
		#define STR0103 ", the Type field remains blank. Due to the field  "
		#define STR0104 " equal to Yes, it is compulsory to fill out the field   "
		#define STR0105 "In folder"
		#define STR0106 ", field   "
		#define STR0107 " was not filled out. This must filled out in order to confirm preparation       "
		#define STR0108 "Unable to load EXL file. Please, check if it is in the data dictionary and in the database. In case of doubts, please, contact Average Tecnologia technical support."
		#define STR0109 "Invoice total"
		#define STR0110 "Enter initial invoice.  "
		#define STR0111 "Invoice input is invalid. Invoice must be input thus: NF01, where 01 is the Invoice number."
		#define STR0112 "Enter final invoice.  "
		#define STR0113 "Invoice input is invalid. Invoice must be input in thus: NF09, where 09 is the Invoice number."
		#define STR0114 "To finith DDE generation, the units of measurement must  "
		#define STR0115 "till "
		#define STR0116 "CNPJ/CPF of the Legal Representative was not entered."
		#define STR0117 "Field "
		#define STR0118 "must be entered, due to the field "
		#define STR0119 " being filled."
		#define STR0120 "Confirm invoice deletion?"
		#define STR0121 "Confirm invoice recovery?"
		#define STR0122 "The Forwarder with the entered CPF was not found in the file of companies.   "
		#define STR0123 "You need to process the return routines before the generation."
	#else
		#define STR0001 "Geração de DDE"
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Gerar"
		#define STR0005 "Retornar"
		#define STR0006 "Diretorio para gravacao do txt não existe ("
		#define STR0007 ") !"
		#define STR0008 "Aviso"
		#define STR0009 "Processo de exportação cancelado"
		#define STR0010 "Processo nao possui dados a visualizar. Prepare a DDE primeiro !"
		#define STR0011 "Atenção"
		#define STR0012 "Processo já possui número de DDE !"
		#define STR0013 "Processo aguardando retorno do Siscomex. Deseja gerar novamente ?"
		#define STR0014 "Incluir"
		#define STR0015 "Alterar"
		#define STR0016 "Excluir"
		#define STR0017 "Processando Arquivo Temporario"
		#define STR0018 "Processo aguardando a geração da DDE !"
		#define STR0019 "Inclusão"
		#define STR0020 "Alteração"
		#define STR0021 "Visualização"
		#define STR0022 "Exclusão"
		#define STR0023 "Nao a dados para "
		#define STR0024 "."
		#define STR0025 "C.G.C./C.P.F. não cadastrado !"
		#define STR0026 "Peso liquido total não pode ser negativo !"
		#define STR0027 "Peso bruto total não pode ser negativo !"
		#define STR0028 "Valor total na condição de venda não pode ser negativo !"
		#define STR0029 " deve ser branco ou ter um valor numérico !"
		#define STR0030 "Quantidade näo pode ser negativa. Informe um valor positivo !"
		#define STR0031 "Erro na criação do arquivo: "
		#define STR0032 "Erro de criação do arquivo: "
		#define STR0033 "Arquivo gerado com sucesso !"
		#define STR0034 "Erro do DOS nro. "
		#define STR0035 "Todos"
		#define STR0036 "Finalizados"
		#define STR0037 "Pendentes"
		#define STR0038 "Pedido"
		#define STR0039 "Sequencia"
		#define STR0040 "Cod. Item"
		#define STR0041 "Descricao"
		#define STR0042 "Preco Unit."
		#define STR0043 "Unid.Medida"
		#define STR0044 "Quantidade "
		#define STR0045 "Vlr.Total  "
		#define STR0046 "Referencia Cliente"
		#define STR0047 "Retorno Siscomex"
		#define STR0048 "Processos:"
		#define STR0049 "Nao ha itens para esta selecao."
		#define STR0050 " Dados do Processo de Embarque: "
		#define STR0051 "Detalhes do arquivo de retorno : "
		#define STR0052 "Nome         : "
		#define STR0053 "Tamanho      : "
		#define STR0054 " bytes"
		#define STR0055 "Data geracao : "
		#define STR0056 "Hora geracao : "
		#define STR0057 "Conteudo do arquivo "
		#define STR0058 "de erro:"
		#define STR0059 "Preparar"
		#define STR0060 "Processo nao tem DDE preparada. Prepare a DDE primeiro !"
		#define STR0061 "Geracäo de DSE"
		#define STR0062 "Processo nao possui dados a visualizar. Gere a DSE primeiro !"
		#define STR0063 "Processo ja possui numero de DSE !"
		#define STR0064 "Processo näo tem DSE preparada. Prepare a DSE primeiro !"
		#define STR0065 " de DSE näo permitida para este embarque, pois existem itens com RE ou DDE."
		#define STR0066 " de DSE näo permitida para este embarque, pois o mesmo ja se encontra embarcado."
		#define STR0067 "Preparacäo"
		#define STR0068 "Geracäo"
		#define STR0069 "NF/Serie: "
		#define STR0070 "A Tabela com a Conversäo de Unidade de Medida näo esta ativa. Ative a tabela e informe as conversöes para as unidades de medida."
		#define STR0071 "Selecione a forma de agrupamento"
		#define STR0072 "Agrupamento"
		#define STR0073 "Item"
		#define STR0074 "N.C.M."
		#define STR0075 "Processo sem geracäo de DSE. Deve-se primeiro gerar a DSE para depois obter o retorno."
		#define STR0076 "Arquivo de retorno näo encontrado."
		#define STR0077 "Retorno da DSE"
		#define STR0078 "Processo : "
		#define STR0079 "Nº. DSE  : "
		#define STR0080 "Data     : "
		#define STR0081 "Hora     : "
		#define STR0082 "Para confirmar o retorno da DSE, escolha o botäo Ok, caso contrario"
		#define STR0083 "Cancelar."
		#define STR0084 "Foram encontradas unidades de medidas sem o cadastro na tabela de Conversäo de Unidades."
		#define STR0085 "  De  "
		#define STR0086 " Para "
		#define STR0087 "Para concluir a geracäo da DSE e necessario que as unidades de medidas"
		#define STR0088 "relacionadas, sejam cadastradas na tabela de conversäo de unidades."
		#define STR0089 "Conversäo da unidade de medida"
		#define STR0090 "Retorno da DSE concluido com sucesso."
		#define STR0091 "A chave de identificacäo do processo que se encontra no arquivo de retorno e invalida."
		#define STR0092 "Estornar"
		#define STR0093 "Processo sem preparacäo de "
		#define STR0094 " para estornar."
		#define STR0095 "Confirma o estorno da preparacäo e geracäo da "
		#define STR0096 "Estorno da "
		#define STR0097 " concluido com sucesso."
		#define STR0098 "Retorno"
		#define STR0099 "Estorno"
		#define STR0100 "A especie näo foi preenchida. Informe a especie primeiro para depois informar a Qtde."
		#define STR0101 "Filial do Exterior näo pode gerar dados para o SISCOMEX !"
		#define STR0102 "Na pasta "
		#define STR0103 ", o campo Tipo näo foi preenchido. Devido o campo "
		#define STR0104 " for igual a Sim e obrigatorio o preenchimento do campo "
		#define STR0105 "N pasta "
		#define STR0106 ", o campo "
		#define STR0107 " näo foi preenchido. O mesmo deve ser preenchido para confirmacäo da preparacäo."
		#define STR0108 "Näo foi possivel carregar o arquivo EXL. Verifique se o mesmo, se encontra no dicionario de dados e na base de dados. Em caso de duvidas entre em contato com o suporte tecnico da Average Tecnologia."
		#define STR0109 "Total de NF's"
		#define STR0110 "Informe a NF de inicial."
		#define STR0111 "A NF informada é invalida. A NF deve ser informada da seguinte forma: NF01, onde 01 é número da NF."
		#define STR0112 "Informe a NF de final."
		#define STR0113 "A NF informada é invalida. A NF deve ser informada da seguinte forma: NF09, onde 09 é número da NF."
		#define STR0114 "Para concluir a geração da DDE é necessário que as unidades de medidas"
		#define STR0115 " até "
		#define STR0116 "CNPJ/CPF do Representante Legal não informado."
		#define STR0117 "O campo "
		#define STR0118 " deve ser informado, devido o campo "
		#define STR0119 " estar preenchido."
		#define STR0120 "Confirma a exclusão da NF?"
		#define STR0121 "Confirma a recuperação da NF?"
		#define STR0122 "O Despachante com o CPF informado não foi encontrado no cadastro de empresas."
		#define STR0123 "Antes da Geração é necessário processar as rotinas de retorno."
	#endif
#endif
